/**
 * FORGE Demo Server — RWA Analysis Agent with x402 Payments
 *
 * This is the demo resource server for the Casper Agentic Buildathon.
 * An AI agent wants to analyze a Real-World Asset (RWA) position.
 * The server charges for each analysis via x402 micropayments on Casper.
 *
 * Flow:
 *   1. Agent requests GET /api/analyze-rwa?asset=real-estate-001
 *   2. Server returns 402 with payment requirements (1 CSPR = 10^9 motes)
 *   3. Agent pays -> server verifies -> settles on Casper -> returns analysis
 *   4. Every payment is logged as an on-chain SettlementEvent
 */

import express from 'express';
import { x402Middleware } from '../middleware.js';
import { csprToMotes } from '../facilitator.js';
import {
  RwaAgent, route as routeQuery, listAssets, getAsset,
  analyzePremium, analyzeBasic, ALL_ASSETS,
} from '../rwa-agent/agent.js';

const app = express();
const PORT = process.env.PORT || 3000;

// Real Casper testnet keypair generated by `casper-client keygen .keys`.
// This is the resource-server wallet that receives x402 payments.
const FORGE_WALLET =
  process.env.FORGE_WALLET ||
  '01f66346cc4db2d0a580b27f75b356a54c814dff74e73ccd44699b53e34e6ee704';

// One shared agent instance for the demo. Premium queries hit the x402-gated
// endpoint below; basic queries are computed locally.
const rwaAgent = new RwaAgent({ serverUrl: process.env.SERVER_URL || `http://localhost:${PORT}` });
const ANALYSIS_PRICE_CSPR = 1;
const ANALYSIS_PRICE_MOTES = csprToMotes(ANALYSIS_PRICE_CSPR);

// The single source of truth for asset data is the analyzer catalogue
// (src/rwa-agent/analyzer.ts → 5 asset classes). The demo server reads from
// there so every listed RWA is analysable on every paid endpoint.
app.get(
  '/api/analyze-rwa',
  x402Middleware({
    amount: ANALYSIS_PRICE_MOTES,
    wallet: FORGE_WALLET,
    description: 'FORGE RWA Analysis',
    chain: 'casper-test',
  }),
  (req, res) => {
    const assetId = (req.query.asset as string) || 'real-estate-001';
    const asset = getAsset(assetId);
    if (!asset) { res.status(404).json({ error: 'RWA not found', assetId }); return; }
    // Full deep-dive so /api/analyze-rwa is consistent with /api/rwa-agent/premium.
    const result = analyzePremium(asset);
    res.json({
      asset: {
        assetId: asset.assetId, type: asset.type, name: asset.name,
        issuer: asset.issuer, location: asset.location,
        valuation: asset.valuation, currency: asset.currency,
      },
      analysisDate: new Date().toISOString(),
      riskAssessment: result.riskAssessment,
      yieldProjection: result.yieldProjection,
      recommendation: result.recommendation,
      deepDive: result.deepDive,
      paymentReceipt: (req as any).paymentReceipt,
    });
  }
);

app.get('/', (_req, res) => {
  res.json({
    service: 'FORGE — RWA Analysis Agent',
    description: 'Autonomous AI agent for RWA analysis on Casper Network',
    pricing: { perAnalysis: `${ANALYSIS_PRICE_CSPR} CSPR`, perAnalysisMotes: ANALYSIS_PRICE_MOTES },
    endpoints: {
      'GET /api/analyze-rwa?asset=ID': 'Full RWA analysis (requires x402 payment)',
      'GET /api/rwa-list': 'List available RWAs (free)',
      'GET /api/rwa-agent/ask?q=<query>': 'Agent routes a natural-language query (free)',
      'GET /api/rwa-agent/portfolio': 'Basic portfolio overview across all RWAs (free)',
      'GET /api/rwa-agent/premium?asset=ID': 'Premium deep-dive analysis (requires x402 payment)',
      'GET /health': 'Health check',
    },
    paymentProtocol: 'x402',
    network: 'casper-test',
    rwaCount: ALL_ASSETS.length,
  });
});

app.get('/api/rwa-list', (_req, res) => {
  const assets = listAssets();
  res.json({ count: assets.length, assets });
});

// --- RWA Agent endpoints -------------------------------------------------

/**
 * Free agent entrypoint: takes a natural-language query, runs the deterministic
 * router, and returns the decision + (for basic/portfolio) the analysis.
 * Demonstrates the agent's reasoning before any payment is required.
 */
app.get('/api/rwa-agent/ask', async (req, res) => {
  const query = (req.query.q as string) || 'overview of the portfolio';
  const decision = routeQuery(query);
  // Serve basic + portfolio directly (no payment). Premium returns the decision
  // + instructions to call the paid premium endpoint.
  if (decision.tier === 'premium' && decision.assetId) {
    const asset = getAsset(decision.assetId);
    return res.json({
      query, decision,
      tier: 'premium',
      message: 'Premium deep-dive requires an x402 payment.',
      premiumEndpoint: `/api/rwa-agent/premium?asset=${decision.assetId}`,
      priceCSPR: ANALYSIS_PRICE_CSPR,
    });
  }
  const result = await rwaAgent.ask(query);
  res.json(result);
});

/**
 * Free portfolio overview: basic analysis across every RWA in the catalogue.
 */
app.get('/api/rwa-agent/portfolio', (_req, res) => {
  const items = ALL_ASSETS.map(analyzeBasic);
  res.json({ count: items.length, items });
});

/**
 * Premium deep-dive analysis — x402 gated. The agent client auto-pays and the
 * middleware verifies + settles the payment on Casper before this handler runs.
 */
app.get(
  '/api/rwa-agent/premium',
  x402Middleware({
    amount: ANALYSIS_PRICE_MOTES,
    wallet: FORGE_WALLET,
    description: 'FORGE RWA Premium Deep-Dive Analysis',
    chain: 'casper-test',
  }),
  (req, res) => {
    const assetId = (req.query.asset as string) || 'real-estate-001';
    const asset = getAsset(assetId);
    if (!asset) { res.status(404).json({ error: 'RWA not found', assetId }); return; }
    const result = analyzePremium(asset);
    res.json({
      result,
      paymentReceipt: (req as any).paymentReceipt,
    });
  }
);

app.get('/health', (_req, res) => {
  res.json({ status: 'healthy', service: 'FORGE', network: 'casper-test' });
});

app.listen(PORT, () => {
  console.log(`\n  FORGE Demo Server running on http://localhost:${PORT}`);
  console.log(`  Network: Casper Testnet`);
  console.log(`  RWA Analysis Price: ${ANALYSIS_PRICE_CSPR} CSPR`);
  console.log(`  Payment Protocol: x402 (HTTP 402)\n`);
});
